<a href="https://colab.research.google.com/github/hamednasr/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.7.0


# introduction to tensors

## tf.constant

In [38]:
a = tf.constant(7)
a

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [39]:
b = tf.constant([3])
b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [40]:
a.ndim

0

In [41]:
b.ndim

1

In [42]:
a.shape

TensorShape([])

In [43]:
b.shape

TensorShape([1])

In [4]:
mat = tf.constant([[2,3],[5,3]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 3]], dtype=int32)>

In [16]:
#float16 is less precision than float32
mat2 = tf.constant([[2,3],[5,3],[8,1]],dtype=tf.float16)
mat2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [5., 3.],
       [8., 1.]], dtype=float16)>

In [18]:
tensor = tf.constant([[[2,3],[5,3],[8,1]],
                      [[2,3],[5,3],[8,1]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[2, 3],
        [5, 3],
        [8, 1]],

       [[2, 3],
        [5, 3],
        [8, 1]]], dtype=int32)>

In [19]:
tensor.ndim

3

## tf.variable

In [22]:
tensor_changable = tf.Variable([[2,3],[5,3]])
tensor_changable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [5, 3]], dtype=int32)>

In [23]:
tensor_changable[0,1] = 9

TypeError: ignored

In [29]:
tensor_changable[1,1].assign(11)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 2,  9],
       [ 5, 11]], dtype=int32)>

#random tensors

In [60]:
rand1 = tf.random.Generator.from_seed(5)
rand1.normal((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.0278524 ,  0.27974114, -0.01347923],
       [ 1.845181  ,  0.97061104, -1.0242516 ]], dtype=float32)>

In [61]:
rand2 = tf.random.Generator.from_seed(5)
rand2.normal((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.0278524 ,  0.27974114, -0.01347923],
       [ 1.845181  ,  0.97061104, -1.0242516 ]], dtype=float32)>

In [62]:
rand1 == rand2

False

In [52]:
rand3 = tf.random.Generator.from_seed(5)
rand3.uniform((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.567016  , 0.2077086 , 0.18223882],
       [0.99883735, 0.36950588, 0.37927854]], dtype=float32)>

## shuffle the elements in tensor

In [10]:
mat = tf.constant([[2,3],[5,3],[4,-2],[8,1]])

In [75]:
tf.random.shuffle(mat,seed=5)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 5,  3],
       [ 4, -2],
       [ 2,  3],
       [ 8,  1]], dtype=int32)>

In [2]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [80]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [3]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [6]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.69941723], shape=(1,), dtype=float32)
tf.Tensor([0.7062043], shape=(1,), dtype=float32)


In [8]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [20]:
tf.random.set_seed(5)
tf.random.shuffle(mat)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4, -2],
       [ 2,  3],
       [ 5,  3],
       [ 8,  1]], dtype=int32)>

## creating tensor from numpy

In [22]:
tf.ones((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [23]:
tf.zeros((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [26]:
num = np.array([[2,3],[5,3],[4,-2],[8,1]])
num

array([[ 2,  3],
       [ 5,  3],
       [ 4, -2],
       [ 8,  1]])

In [32]:
mat_con = tf.constant(num,shape=(2,4),dtype=tf.float16)
mat_con

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[ 2.,  3.,  5.,  3.],
       [ 4., -2.,  8.,  1.]], dtype=float16)>

In [33]:
mat_var = tf.Variable(num,dtype=tf.float16)
mat_var

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float16, numpy=
array([[ 2.,  3.],
       [ 5.,  3.],
       [ 4., -2.],
       [ 8.,  1.]], dtype=float16)>

In [34]:
mat_var[3,1].assign(9)

<tf.Variable 'UnreadVariable' shape=(4, 2) dtype=float16, numpy=
array([[ 2.,  3.],
       [ 5.,  3.],
       [ 4., -2.],
       [ 8.,  9.]], dtype=float16)>

## Getting more info from tensors

In [36]:
mat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 5,  3],
       [ 4, -2],
       [ 8,  1]], dtype=int32)>

In [37]:
mat.shape

TensorShape([4, 2])

In [46]:
zeros = tf.zeros((2,3,4,5))
zeros

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
zeros.shape

TensorShape([2, 3, 4, 5])

In [52]:
zeros[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [56]:
zeros.shape, zeros.ndim, tf.size(zeros)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [60]:
zeros[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [67]:
dim2tensor= tf.constant(np.arange(1,12,2).reshape(3,2))
dim2tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])>

In [68]:
dim2tensor.shape, dim2tensor.ndim

(TensorShape([3, 2]), 2)

In [69]:
dim2tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 11])>

In [74]:
dim3tensor = dim2tensor[tf.newaxis,...]
dim3tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int64, numpy=
array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]]])>

In [75]:
dim3tensor = dim2tensor[...,tf.newaxis]
dim3tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int64, numpy=
array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]])>

In [77]:
#3,1,2
dim3tensor = dim2tensor[:,tf.newaxis,:]
dim3tensor

<tf.Tensor: shape=(3, 1, 2), dtype=int64, numpy=
array([[[ 1,  3]],

       [[ 5,  7]],

       [[ 9, 11]]])>

In [80]:
tf.expand_dims(dim2tensor,axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=int64, numpy=
array([[[ 1,  3]],

       [[ 5,  7]],

       [[ 9, 11]]])>

##manipulating tensors
**basic operations** : 
 '+ , - , * , /'

In [83]:
dim2tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])>

In [81]:
dim2tensor+10

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[11, 13],
       [15, 17],
       [19, 21]])>

In [82]:
dim2tensor*2

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 2,  6],
       [10, 14],
       [18, 22]])>

In [84]:
dim2tensor/3

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.33333333, 1.        ],
       [1.66666667, 2.33333333],
       [3.        , 3.66666667]])>

In [85]:
tf.multiply(dim2tensor,2)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 2,  6],
       [10, 14],
       [18, 22]])>

## matrix multiplication

In [2]:
dim2tensor= tf.constant(np.arange(1,12,2).reshape(3,2))
dim2tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])>

In [9]:
tf.transpose(dim2tensor,perm=(0,1))

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])>

In [10]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [12]:
tf.transpose(x, perm=[1,0, 2])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]], dtype=int32)>

In [15]:
tf.cast(dim2tensor,dtype=tf.int8)

<tf.Tensor: shape=(3, 2), dtype=int8, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]], dtype=int8)>